
package ifmo.lab3.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.7-b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CountriesWebService", targetNamespace = "http://lab3.ifmo/", wsdlLocation = "http://localhost:8080/CountriesWebService?wsdl")
public class CountriesWebService
    extends Service
{

    private final static URL COUNTRIESWEBSERVICE_WSDL_LOCATION;
    private final static WebServiceException COUNTRIESWEBSERVICE_EXCEPTION;
    private final static QName COUNTRIESWEBSERVICE_QNAME = new QName("http://lab3.ifmo/", "CountriesWebService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/CountriesWebService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        COUNTRIESWEBSERVICE_WSDL_LOCATION = url;
        COUNTRIESWEBSERVICE_EXCEPTION = e;
    }

    public CountriesWebService() {
        super(__getWsdlLocation(), COUNTRIESWEBSERVICE_QNAME);
    }

    public CountriesWebService(WebServiceFeature... features) {
        super(__getWsdlLocation(), COUNTRIESWEBSERVICE_QNAME, features);
    }

    public CountriesWebService(URL wsdlLocation) {
        super(wsdlLocation, COUNTRIESWEBSERVICE_QNAME);
    }

    public CountriesWebService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, COUNTRIESWEBSERVICE_QNAME, features);
    }

    public CountriesWebService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CountriesWebService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CountriesErrorHandlingService
     */
    @WebEndpoint(name = "CountriesErrorHandlingServicePort")
    public CountriesErrorHandlingService getCountriesErrorHandlingServicePort() {
        return super.getPort(new QName("http://lab3.ifmo/", "CountriesErrorHandlingServicePort"), CountriesErrorHandlingService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CountriesErrorHandlingService
     */
    @WebEndpoint(name = "CountriesErrorHandlingServicePort")
    public CountriesErrorHandlingService getCountriesErrorHandlingServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://lab3.ifmo/", "CountriesErrorHandlingServicePort"), CountriesErrorHandlingService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (COUNTRIESWEBSERVICE_EXCEPTION!= null) {
            throw COUNTRIESWEBSERVICE_EXCEPTION;
        }
        return COUNTRIESWEBSERVICE_WSDL_LOCATION;
    }

}
