
package ifmo.lab1.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.7-b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CountriesService", targetNamespace = "http://lab1.ifmo/", wsdlLocation = "http://localhost:8080/ws_labs_war_exploded/CountriesService?wsdl")
public class CountriesService
    extends Service
{

    private final static URL COUNTRIESSERVICE_WSDL_LOCATION;
    private final static WebServiceException COUNTRIESSERVICE_EXCEPTION;
    private final static QName COUNTRIESSERVICE_QNAME = new QName("http://lab1.ifmo/", "CountriesService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/ws_labs_war_exploded/CountriesService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        COUNTRIESSERVICE_WSDL_LOCATION = url;
        COUNTRIESSERVICE_EXCEPTION = e;
    }

    public CountriesService() {
        super(__getWsdlLocation(), COUNTRIESSERVICE_QNAME);
    }

    public CountriesService(WebServiceFeature... features) {
        super(__getWsdlLocation(), COUNTRIESSERVICE_QNAME, features);
    }

    public CountriesService(URL wsdlLocation) {
        super(wsdlLocation, COUNTRIESSERVICE_QNAME);
    }

    public CountriesService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, COUNTRIESSERVICE_QNAME, features);
    }

    public CountriesService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CountriesService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CountriesWebService
     */
    @WebEndpoint(name = "CountriesWebServicePort")
    public CountriesWebService getCountriesWebServicePort() {
        return super.getPort(new QName("http://lab1.ifmo/", "CountriesWebServicePort"), CountriesWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CountriesWebService
     */
    @WebEndpoint(name = "CountriesWebServicePort")
    public CountriesWebService getCountriesWebServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://lab1.ifmo/", "CountriesWebServicePort"), CountriesWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (COUNTRIESSERVICE_EXCEPTION!= null) {
            throw COUNTRIESSERVICE_EXCEPTION;
        }
        return COUNTRIESSERVICE_WSDL_LOCATION;
    }

}
