
package ifmo.lab1.service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.7-b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CountriesWebService", targetNamespace = "http://lab1.ifmo/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CountriesWebService {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<ifmo.lab1.service.Country>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCountries", targetNamespace = "http://lab1.ifmo/", className = "ifmo.lab1.service.GetCountries")
    @ResponseWrapper(localName = "getCountriesResponse", targetNamespace = "http://lab1.ifmo/", className = "ifmo.lab1.service.GetCountriesResponse")
    @Action(input = "http://lab1.ifmo/CountriesWebService/getCountriesRequest", output = "http://lab1.ifmo/CountriesWebService/getCountriesResponse")
    public List<Country> getCountries(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns ifmo.lab1.service.Country
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCountry", targetNamespace = "http://lab1.ifmo/", className = "ifmo.lab1.service.GetCountry")
    @ResponseWrapper(localName = "getCountryResponse", targetNamespace = "http://lab1.ifmo/", className = "ifmo.lab1.service.GetCountryResponse")
    @Action(input = "http://lab1.ifmo/CountriesWebService/getCountryRequest", output = "http://lab1.ifmo/CountriesWebService/getCountryResponse")
    public Country getCountry(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
