
package ifmo.lab2.service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.7-b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CountriesWebServiceCrud", targetNamespace = "http://lab2.ifmo/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CountriesWebServiceCrud {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addCountry", targetNamespace = "http://lab2.ifmo/", className = "ifmo.lab2.service.AddCountry")
    @ResponseWrapper(localName = "addCountryResponse", targetNamespace = "http://lab2.ifmo/", className = "ifmo.lab2.service.AddCountryResponse")
    @Action(input = "http://lab2.ifmo/CountriesWebServiceCrud/addCountryRequest", output = "http://lab2.ifmo/CountriesWebServiceCrud/addCountryResponse")
    public String addCountry(
        @WebParam(name = "arg0", targetNamespace = "")
        Country arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns ifmo.lab2.service.ResponseCode
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateCountry", targetNamespace = "http://lab2.ifmo/", className = "ifmo.lab2.service.UpdateCountry")
    @ResponseWrapper(localName = "updateCountryResponse", targetNamespace = "http://lab2.ifmo/", className = "ifmo.lab2.service.UpdateCountryResponse")
    @Action(input = "http://lab2.ifmo/CountriesWebServiceCrud/updateCountryRequest", output = "http://lab2.ifmo/CountriesWebServiceCrud/updateCountryResponse")
    public ResponseCode updateCountry(
        @WebParam(name = "arg0", targetNamespace = "")
        Country arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns ifmo.lab2.service.ResponseCode
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteCountry", targetNamespace = "http://lab2.ifmo/", className = "ifmo.lab2.service.DeleteCountry")
    @ResponseWrapper(localName = "deleteCountryResponse", targetNamespace = "http://lab2.ifmo/", className = "ifmo.lab2.service.DeleteCountryResponse")
    @Action(input = "http://lab2.ifmo/CountriesWebServiceCrud/deleteCountryRequest", output = "http://lab2.ifmo/CountriesWebServiceCrud/deleteCountryResponse")
    public ResponseCode deleteCountry(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<ifmo.lab2.service.Country>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCountries", targetNamespace = "http://lab2.ifmo/", className = "ifmo.lab2.service.GetCountries")
    @ResponseWrapper(localName = "getCountriesResponse", targetNamespace = "http://lab2.ifmo/", className = "ifmo.lab2.service.GetCountriesResponse")
    @Action(input = "http://lab2.ifmo/CountriesWebServiceCrud/getCountriesRequest", output = "http://lab2.ifmo/CountriesWebServiceCrud/getCountriesResponse")
    public List<Country> getCountries(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns ifmo.lab2.service.Country
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCountry", targetNamespace = "http://lab2.ifmo/", className = "ifmo.lab2.service.GetCountry")
    @ResponseWrapper(localName = "getCountryResponse", targetNamespace = "http://lab2.ifmo/", className = "ifmo.lab2.service.GetCountryResponse")
    @Action(input = "http://lab2.ifmo/CountriesWebServiceCrud/getCountryRequest", output = "http://lab2.ifmo/CountriesWebServiceCrud/getCountryResponse")
    public Country getCountry(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
